#!/bin/sh

chmod -R 755 "$3/System/Library/Extensions/AppleHDA.kext"
chown -R root:wheel "$3/System/Library/Extensions/AppleHDA.kext"
chmod -R 755 "$3/System/Library/Extensions/HDAEnabler.kext"
chown -R root:wheel "$3/System/Library/Extensions/HDAEnabler.kext"
rm -rf "$3/System/Library/Caches/com.apple.kext.caches/Startup/Extensions.mkext"
